name: Postman collection workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 02 * * *'
    - cron: '00 14 * * *'
    - cron: '00 06 * * 1-5'

# Added explicit write permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-postman-tester:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Node.js and npm  
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install newman and Html-extra globally 
        run: |
          npm install -g newman 
          npm install -g newman-reporter-htmlextra

      - name: Run the postman collection with newman
        run: |
          mkdir -p newman
          newman run "Inwarranty-flow Collection.postman_collection.json" \
          -e QA.postman_environment.json \
          -d testData.csv \
          -r cli,htmlextra \
          --reporter-htmlextra-export newman/index.html
          
      - name: Newman report    
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: postman-html-report
          path: newman/index.html

      - name: creating github page branch   
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./newman  # Fixed syntax with space
